"""add region to users

Revision ID: 0178582a436b
Revises: ba265568f6c2
Create Date: 2025-09-22 23:43:48.903335+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0178582a436b'
down_revision: Union[str, Sequence[str], None] = 'ba265568f6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_region'), 'users', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_region'), table_name='users')
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
