"""ajuste clinical_histories con campos canónicos

Revision ID: 6f8fe63af411
Revises: 6176ab79fc23
Create Date: 2025-09-22 20:42:02.197305+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f8fe63af411'
down_revision: Union[str, Sequence[str], None] = '6176ab79fc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_histories', sa.Column('antecedentes_personales', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('antecedentes_familiares', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('medicacion_actual', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('alergias', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('diagnosticos_previos', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('consumo', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('antecedentes_psico', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('clinical_histories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('clinical_histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_clinical_histories_id'), 'clinical_histories', ['id'], unique=False)
    op.drop_column('clinical_histories', 'allergies')
    op.drop_column('clinical_histories', 'medication')
    op.drop_column('clinical_histories', 'background')
    op.drop_column('clinical_histories', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_histories', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinical_histories', sa.Column('background', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinical_histories', sa.Column('medication', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinical_histories', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clinical_histories_id'), table_name='clinical_histories')
    op.alter_column('clinical_histories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('clinical_histories', 'updated_at')
    op.drop_column('clinical_histories', 'notas')
    op.drop_column('clinical_histories', 'antecedentes_psico')
    op.drop_column('clinical_histories', 'consumo')
    op.drop_column('clinical_histories', 'diagnosticos_previos')
    op.drop_column('clinical_histories', 'alergias')
    op.drop_column('clinical_histories', 'medicacion_actual')
    op.drop_column('clinical_histories', 'antecedentes_familiares')
    op.drop_column('clinical_histories', 'antecedentes_personales')
    # ### end Alembic commands ###
