"""add doctor_settings table

Revision ID: a1dd293b1378
Revises: 144387a4c8e1
Create Date: 2025-09-23 18:14:23.022946+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dd293b1378'
down_revision: Union[str, Sequence[str], None] = '144387a4c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_settings',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('doctor_id', name='uq_doctor_settings_doctor')
    )
    op.create_index(op.f('ix_doctor_settings_doctor_id'), 'doctor_settings', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_settings_doctor_id'), table_name='doctor_settings')
    op.drop_table('doctor_settings')
    # ### end Alembic commands ###
