"""therapeutic_plans campos finales

Revision ID: ba265568f6c2
Revises: 6f8fe63af411
Create Date: 2025-09-22 21:28:36.164855+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba265568f6c2'
down_revision: Union[str, Sequence[str], None] = '6f8fe63af411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapeutic_plans', sa.Column('objetivos', sa.Text(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('frecuencia', sa.Text(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('intervenciones', sa.Text(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('tareas', sa.Text(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('metricas', sa.Text(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('proxima_revision', sa.Date(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('therapeutic_plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('therapeutic_plans', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('therapeutic_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_column('therapeutic_plans', 'interventions')
    op.drop_column('therapeutic_plans', 'notes')
    op.drop_column('therapeutic_plans', 'frequency')
    op.drop_column('therapeutic_plans', 'goals')
    op.drop_column('therapeutic_plans', 'tasks')
    op.drop_column('therapeutic_plans', 'metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapeutic_plans', sa.Column('metrics', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('therapeutic_plans', sa.Column('tasks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('therapeutic_plans', sa.Column('goals', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('therapeutic_plans', sa.Column('frequency', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('therapeutic_plans', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('therapeutic_plans', sa.Column('interventions', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('therapeutic_plans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('therapeutic_plans', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('therapeutic_plans', 'updated_at')
    op.drop_column('therapeutic_plans', 'notas')
    op.drop_column('therapeutic_plans', 'proxima_revision')
    op.drop_column('therapeutic_plans', 'metricas')
    op.drop_column('therapeutic_plans', 'tareas')
    op.drop_column('therapeutic_plans', 'intervenciones')
    op.drop_column('therapeutic_plans', 'frecuencia')
    op.drop_column('therapeutic_plans', 'objetivos')
    # ### end Alembic commands ###
